version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kleros-k-pong:latest
    container_name: kleros-k-pong
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - k-pong-network

  postgres:
    image: postgres:15-alpine
    container_name: k-pong-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: k_pong
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - k-pong-network

networks:
  k-pong-network:
    driver: bridge

volumes:
  postgres_data: 